---
# Problem set 1 configuration
images:
  input0: ../Resources/ProblemSet1/ps1-input0.png
  input0_noise: ../Resources/ProblemSet1/ps1-input0-noise.png
  input1: ../Resources/ProblemSet1/ps1-input1.png
  input2: ../Resources/ProblemSet1/ps1-input2.png
  input3: ../Resources/ProblemSet1/ps1-input3.png
output_dir: ./ps1_output

# Problem 2 configuration
# Edge detector options
edge_detector_p2:
  gaussian_size: 1
  gaussian_sigma: 0.0001
  lower_threshold: 1
  upper_threshold: 3
  sobel_aperture_size: 3

hough_transform_p2:
  rho_bin_size: 2
  theta_bin_size: 2
  num_peaks: 6
  threshold: 200

# Problem 3 configuration
edge_detector_p3:
  gaussian_size: 23
  gaussian_sigma: 6
  lower_threshold: 7
  upper_threshold: 10
  sobel_aperture_size: 7

hough_transform_p3:
  rho_bin_size: 2
  theta_bin_size: 2
  num_peaks: 6
  threshold: 10
...