---
# Problem Set 4 configuration
images:
  transA.jpg: ../Resources/ProblemSet4/transA.jpg
  transB.jpg: ../Resources/ProblemSet4/transB.jpg
  simA.jpg: ../Resources/ProblemSet4/simA.jpg
  simB.jpg: ../Resources/ProblemSet4/simB.jpg
  check.bmp: ../Resources/ProblemSet4/check.bmp
  check_rot.bmp: ../Resources/ProblemSet4/check_rot.bmp

output_dir: ./ps4_output

# Seed for Mersenne Twister Engine
mersenne_seed: 16 38 c7 e4 6a a2 d8 cc 96 f6 fe f1 4b 7d a7 25

use_gpu: true

harris_trans:
  sobel_kernel_size: 3
  window_size: 5
  gaussian_sigma: 1.5
  alpha: 0.04
  response_threshold: 500000000
  min_distance: 5

harris_sim:
  sobel_kernel_size: 3
  window_size: 5
  gaussian_sigma: 1.5
  alpha: 0.04
  response_threshold: 500000000
  min_distance: 5

ransac_trans:
  reprojection_threshold: 10
  max_iterations: 2000
  consensus_ratio: 0.2

ransac_sim:
  reprojection_threshold: 6
  max_iterations: 2000
  consensus_ratio: 0.6

ransac_affine:
  reprojection_threshold: 6
  max_iterations: 2000
  consensus_ratio: 0.6
...